apiVersion: batch/v1
kind: CronJob
metadata:
  name: indexed-cronjob
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      containers:
      - name: 'worker'
        image: exampleregistry19062021.azurecr.io/myworker
        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: postgres-password