apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
  - name: backend-api
    protocol: TCP
    port: 80
  selector:
    app: backend
